db:
  username: postgres
  password: pass
  driver: PostgresDriver
  url: postgres:5433
  hosts: localhost,127.0.0.1

  pool:
    size: 12
    timeout: 10
  pools:
    - size: 1
      timeout: 1
    - size: 2
      timeout: 2
    - size: 3
      timeout: 3

  logging:
    level:
      root: INFO
    file:
      name: application.log
      path: /